services:
  app:
    image: gathering-21-build:latest
    environment:
      REDIS_HOST: gathering_project-redis-1
      REDIS_PORT: 6379
      SPRING_DATASOURCE_INITIALIZATION_MODE: always  # 스프링부트에서 데이터베이스 초기화 로직을 실행할 수 있도록 설정
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - app-network
    restart: on-failure

  redis:
    image: redis:latest
    container_name: gathering_project-redis-1
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - app-network
    volumes:
      - redis-data:/data
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  redis-data:

