services:
  app:
    image: gathering-21-build:latest
    environment:
      DEV_DB_HOST: gathering_project-db-1
      REDIS_HOST: gathering_project-redis-1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${DEV_SERVER_PORT}:${DEV_SERVER_PORT}"
    env_file:
      - .env.dev
    depends_on:
      - db
      - redis
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: gathering_project-db-1
    environment:
      MYSQL_ROOT_PASSWORD: ${DEV_DB_PASS}
      MYSQL_DATABASE: ${DEV_DB_NAME}
    ports:
      - "${DEV_DB_PORT}:${DEV_DB_PORT}"
    networks:
      - app-network
    volumes:
      - db-data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: gathering_project-redis-1
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    networks:
      - app-network
    volumes:
      - redis-data:/data

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
  redis-data:
