server:
  port: ${PROD_SERVER_PORT}

spring:
  config:
    import: optional:file:.env.prod[.properties]
  datasource:
    url: jdbc:mysql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}?useSSL=false&serverTimezone=Asia/Seoul
    username: ${PROD_DB_USER}
    password: ${PROD_DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true

logging:
  level:
    root: INFO

jwt:
  secret: ${JWT_SECRET_KEY}