name: Dev CI

on:
  push:
    branches:
      - dev  # dev 브랜치에 푸시될 때 실행
  pull_request:
    branches:
      - dev  # dev 브랜치에 대한 PR 생성 시 실행

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # Gradle Wrapper에 실행 권한 부여
      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew

      # 2. Gradle 의존성 캐시 사용
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches/modules-2/files-2.1
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle

      # 3. JDK 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 4. Linting 및 코드 품질 검사
      - name: Run Checkstyle
        run: ./gradlew checkstyleMain

      # Checkstyle HTML 리포트 저장
      - name: Archive Checkstyle HTML report
        uses: actions/upload-artifact@v3
        with:
          name: checkstyle-html-report
          path: build/reports/checkstyle/main.html

      # 5. 빌드 및 테스트 실행
      - name: Build and run tests
        run: |
          ./gradlew build test

    env:
      DEV_SERVER_PORT: ${{ secrets.DEV_SERVER_PORT }}
      DEV_DB_HOST: ${{ secrets.DEV_DB_HOST }}
      DEV_DB_PORT: ${{ secrets.DEV_DB_PORT }}
      DEV_DB_NAME: ${{ secrets.DEV_DB_NAME }}
      DEV_DB_USER: ${{ secrets.DEV_DB_USER }}
      DEV_DB_PASS: ${{ secrets.DEV_DB_PASS }}
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}

      # OAuth2 (Kakao) 설정
      KAKAO_CLIENT_ID: ${{ secrets.KAKAO_CLIENT_ID }}
      KAKAO_CLIENT_SECRET: ${{ secrets.KAKAO_CLIENT_SECRET }}

      # AWS S3 설정
      S3_PLACE: ${{ secrets.S3_PLACE }}
      S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
      S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
      S3_URL: ${{ secrets.S3_URL }}
      S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}

      # 기본 프로필 이미지 URL
      DEFAULT_PROFILE_IMAGE_URL: ${{ secrets.DEFAULT_PROFILE_IMAGE_URL }}



